Selector/urls.py
from django.contrib import admin
from django.urls import path
from App import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.products_list, name = "home"),

    path('add_supplier_card', views.add_supplier_card, name = "add_supplier_card"),

    path('add_category', views.add_category, name='add_category'),

    path('categories', views.category_list, name='category_list'),

    path('suppliers', views.supplier_card_list, name='supplier_card_list'),

    path('products', views.products_list, name='products_list'),

    path('add_product', views.add_products, name='add_product'),

    path('supplier_detail/<int:supplier_id>/', views.supplier_detail, name='supplier_detail'),

    path('edit_supplier_card/<int:supplier_id>', views.edit_supplier_card, name = "edit_supplier_card"),

    path('edit_product/<int:product_id>', views.edit_product, name="edit_product"),

    path('search', views.shearch_product, name="search_product"),

    #
    # path('delete_supplier_card', views.delete_supplier_card, name = "delete_supplier_card")
]

App/models/category.py
from django.db import models

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, verbose_name="Наименование категории",
        unique=True,
        error_messages={
            'unique': "Категория с таким наименованием уже существует!"
        })
    parent_category_id = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категория"

App/models/product.py
from django.db import models

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    category_id = models.ForeignKey('Category', null=True, blank=True, on_delete=models.CASCADE)
    suppliers_id = models.ManyToManyField('SupplierCard')
    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт (товар) "
        verbose_name_plural = "Продукт (товар) "

App/models/supplier_card.py
from django.db import models
from django.urls import reverse

class SupplierCard(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, verbose_name="Наименование карточки поставщика",
        unique=True,
        error_messages={
            'unique': "Поставщик с таким наименованием уже существует!"
        })
    address = models.CharField(max_length=255, verbose_name="Адрес поставщика")
    rating_choices = (
        ('low', 'Низкий'),
        ('medium', 'Средний'),
        ('high', 'Высокий')
    )
    rating = models.CharField(max_length=10, choices=rating_choices, verbose_name="Ценовой рейтинг поставщика")
    categories = models.ManyToManyField('Category', verbose_name="Категория")
    contacts = models.CharField(max_length=150, default=' ', verbose_name="Контактная информация")
    description = models.TextField(verbose_name="Описание")
    created_at = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Карточка поставщика"
        verbose_name_plural = "Карточка поставщика"

App/forms.py
from django import forms
from .models import SupplierCard, Category, Product

class SupplierCardForm(forms.ModelForm):
    class Meta:
        model = SupplierCard
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

App/views/category.py
from django.shortcuts import render, redirect
from App.models import Category
from ..forms import CategoryForm


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = CategoryForm()
    return render(request, 'category/add.html', {'form': form})


def category_list(request):
    categories = Category.objects.all()
    return render(request, 'category/categories.html', {'categories': categories})

App/views/product.py
from django.shortcuts import render, redirect, get_object_or_404
from App.models import Product
from ..forms import ProductForm
from django.core.paginator import Paginator


def add_products(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products_list')
    else:
        form = ProductForm()
    return render(request, 'product/add.html', {'form': form})


def edit_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products_list')
    else:
        form = ProductForm(instance=product)
    return render(request, 'product/edit.html', {'form': form, 'product': product})


def shearch_product(request):
    # https://django.fun/ru/docs/django/4.1/ref/contrib/postgres/search/
    query = request.GET.get('query')
    results = Product.objects.filter(name__iregex=query)

    return render(request, 'product/search_results.html', {"results": results})


def products_list(request):
    all_objects = Product.objects.all()
    paginator = Paginator(all_objects, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'product/products.html', {'page_obj': page_obj})

App/views/supplier_card.py
from django.shortcuts import render, redirect, get_object_or_404
from App.models import SupplierCard
from ..forms import SupplierCardForm


def supplier_card_list(request):
    supplier_cards = SupplierCard.objects.all()
    return render(request, 'supcard/sup_cards.html', {'supplier_cards': supplier_cards})


def add_supplier_card(request):
    if request.method == 'POST':
        form = SupplierCardForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('supplier_card_list')
    else:
        form = SupplierCardForm()
    return render(request, 'supcard/add.html', {'form': form})

def supplier_detail(request, supplier_id):
    if request.method == 'GET':
        supplier_card = SupplierCard.objects.get(id=supplier_id)
        return render(request, 'supcard/supcard.html', {'supplier_card':supplier_card})

def edit_supplier_card(request, supplier_card_id):
    supplier_card = get_object_or_404(SupplierCard, id=supplier_card_id)

    if request.method == 'POST':
        form = SupplierCardForm(request.POST, instance=supplier_card)
        if form.is_valid():
            form.save()
            return redirect('supplier_card_detail', supplier_card_id=supplier_card.id)
    else:
        form = SupplierCardForm(instance=supplier_card)
    return render(request, 'supcard/edit.html', {'form': form, 'supplier_card': supplier_card})

App/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- Bootstrap icons CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    <title>{% block title %}Home{% endblock title %}</title>
</head>
<body>
    <div class="search-panel">
        <a class="button-link" href="{% url 'home' %}"><h1 class="selector-block">Selector</h1></a>
        <form class="input-group" method="GET" action="{% url 'search_product' %}">
            {% csrf_token %}
            <input type="text" name="query" class="form-control" placeholder="Введите запрос...">
            <button class="btn btn-primary btn-search" type="submit">
                <i class="bi bi-search"></i>
            </button>
        </form>
    </div>
    {% block content %}
    {% endblock %}

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

App/templates/category/add.html
{% extends "base.html" %}

{% block content %}
 <div class="form-container">
     <h2>Добавление категории</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
          {% if form.email.errors %}
    <ul class="errorlist">
      {% for error in form.email.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
        <button class="save-button" type="submit">Сохранить</button>
    </form>
 </div>
{% endblock %}

App/templates/category/categories.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h1 class="h3 mt-4 mb-3">Categories</h1>

    {% if categories %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <!-- Add more fields here as needed -->
          </tr>
        </thead>
        <tbody>
          {% for category in categories %}
            <tr>
              <td>{{ category.id }}</td>
              <td>{{ category.name }}</td>
              <!-- Render additional fields here -->
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No categories found.</p>
    {% endif %}
  </div>
{% endblock %}

App/templates/home.html
{%extends 'base.html' %}
{%include 'product/products.html' %}

App/templates/product/add.html
{% extends "base.html" %}
{% block content %}

 <div class="form-container">
     <h2>Добавление товара</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if form.email.errors %}
    <ul class="errorlist">
      {% for error in form.email.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
        <button class="save-button" type="submit">Сохранить</button>
    </form>
 </div>
{% endblock %}

App/templates/product/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>Редактировать товар</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

App/templates/product/products.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .product-item {
            background-color: white;
            border: 1px solid black;
            border-radius: 10px;
            margin-bottom: 20px;
            padding: 10px;
        }

        .supplier-list {
        }

        .supplier-item {
            border-radius: 20px;
            margin-bottom: 10px;
            text-align: center;
            cursor: pointer;
        }
        .pagination {
          display: flex;
          justify-content: center;
          align-items: flex-end;
        }

        .pagination .step-links a {
          margin: 0 5px;
          padding: 5px 10px;
          border: 1px solid #ccc;
          border-radius: 3px;
          text-decoration: none;
          color: #333;
        }

        .pagination .current-page {
          font-weight: bold;
          color: #333;
          background-color: #fff;
        }
        </style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% for product in page_obj %}
                <div class="product-item">
                    <p>{{ product.name }}</p>
                    <p>Category: {{ product.category_id }}</p>
                   <div class="supplier-list"> {% for supplier_card in product.suppliers_id.all %}
                       <a href="{% url 'supplier_detail' supplier_card.id %}">
                           <div class="supplier-item p-2 {% if supplier_card.rating == 'low' %}bg-danger{% elif supplier_card.rating == 'medium' %}bg-warning{% else %}bg-success{% endif %} text-white">
                             {{ supplier_card.name }}
                            </div>
                        </a>
                           {% endfor %}
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;</a>
            <a href="?page={{ page_obj.previous_page_number }}"><</a>
        {% endif %}

        <span class="current-page">{{ page_obj.number }}</span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

App/templates/product/search_results.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .product-item {
            background-color: white;
            border: 1px solid black;
            border-radius: 10px;
            margin-bottom: 20px;
            padding: 10px;
        }

        .supplier-list {
        }

        .supplier-item {
            border-radius: 20px;
            margin-bottom: 10px;
            text-align: center;
            cursor: pointer;
        }
        </style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% for product in results %}
                <div class="product-item">
                    <p>{{ product.name }}</p>
                    <p>Category: {{ product.category_id }}</p>
                   <div class="supplier-list"> {% for supplier_card in product.suppliers_id.all %}
                       <a href="{% url 'supplier_detail' supplier_card.id %}">
                           <div class="supplier-item p-2 {% if supplier_card.rating == 'low' %}bg-danger{% elif supplier_card.rating == 'medium' %}bg-warning{% else %}bg-success{% endif %} text-white">
                             {{ supplier_card.name }}
                            </div>
                        </a>
                           {% endfor %}
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

App/templates/supcard/add.html
{% extends "base.html" %}
{% block content %}
 <div class="form-container">
         <h2 align="center">Добавление карточки поставщика</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if form.email.errors %}
    <ul class="errorlist">
      {% for error in form.email.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
        <button class="save-button" type="submit">Сохранить</button>
    </form>
 </div>
{% endblock %}

App/templates/supcard/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>Редактировать карточку поставщика</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

App/templates/supcard/sup_cards.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h1 class="text-center">Supplier Cards</h1>

    <div class="row justify-content-center">
      {% if supplier_cards %}
        {% for supplier_card in supplier_cards %}
          <div class="col-md-6">
            <div class="card mb-3 {% if supplier_card.rating == 'low' %}bg-danger{% elif supplier_card.rating == 'medium' %}bg-warning{% else %}bg-success{% endif %} text-white">
              <div class="card-body">
                <h5 class="card-title">{{ supplier_card.name }}</h5>
                <hr class="bg-white">
                <p class="card-text"><strong>ID:</strong> {{ supplier_card.id }}</p>
                <p class="card-text"><strong>Address:</strong> {{ supplier_card.address }}</p>
                <p class="card-text"><strong>Rating:</strong> {{ supplier_card.get_rating_display }}</p>
                <p class="card-text"><strong>Categories:</strong> {% for categ in supplier_card.categories.all  %} {{categ}}/ {% endfor %}</p>
                <p class="card-text"><strong>Contacts:</strong> {{ supplier_card.contacts }}</p>
                <p class="card-text"><strong>Description:</strong> {{ supplier_card.description }}</p>
                <!-- Add more fields here as needed -->
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="col-md-6">
          <p class="text-center">No supplier cards found.</p>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

App/templates/supcard/supcard.html
{% extends 'base.html' %}

{% block content %}
          <div class="col-md-6 mx-auto">
            <div class="card mb-3 {% if supplier_card.rating == 'low' %}bg-danger{% elif supplier_card.rating == 'medium' %}bg-warning{% else %}bg-success{% endif %} text-white">
              <div class="card-body">
                <h5 class="card-title">{{ supplier_card.name }}</h5>
                <hr class="bg-white">
                <p class="card-text"><strong>ID:</strong> {{ supplier_card.id }}</p>
                <p class="card-text"><strong>Address:</strong> {{ supplier_card.address }}</p>
                <p class="card-text"><strong>Rating:</strong> {{ supplier_card.get_rating_display }}</p>
                <p class="card-text"><strong>Categories:</strong> {% for categ in supplier_card.categories.all  %} {{categ}}/ {% endfor %}</p>
                <p class="card-text"><strong>Contacts:</strong> {{ supplier_card.contacts }}</p>
                <p class="card-text"><strong>Description:</strong> {{ supplier_card.description }}</p>
                <!-- Add more fields here as needed -->
              </div>
            </div>
          </div>
{% endblock %}